name: Kitchen Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

# For reusable workflows, the permissions setting for id-token should be set to write at the
# caller workflow level or in the specific job that calls the reusable workflow.

permissions:
  id-token: write

jobs:
  kitchen_terraform:
    name: "Tests"
    uses: osinfra-io/github-terraform-gcp-called-workflows/.github/workflows/kitchen-terraform.yml@v0.2.1
    if: github.actor != 'dependabot[bot]' && github.actor != 'osinfra-sa'

    with:
      service_account: "plt-lz-testing-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com"
      workload_identity_provider: "projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc"

    secrets:
      billing_account: ${{ secrets.BILLING_ACCOUNT }}
