name: Kitchen Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

# For reusable workflows, the permissions setting for id-token should be set to write at the
# caller workflow level or in the specific job that calls the reusable workflow.

permissions:
  id-token: write

jobs:
  kittchen_terraform:
    name: "Kitchen-Terraform"
    uses: osinfra-io/github-terraform-gcp-called-workflows/.github/workflows/kitchen-terraform.yml@v0.1.1
    if: github.actor != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Sandbox Infrastructure: Global"
      service_account: "plt-lz-testing-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com"
      terraform_state_bucket: "plt-lz-testing-2c8b-sb"
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: global-sandbox
      working_directory: test
      workload_identity_provider: "projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc"
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      terraform_plan_secret_args: -var="billing_account=${{ secrets.BILLING_ACCOUNT }}"
